services:

    nginx:
        build:
            context: .
            target: production-server
            dockerfile: Dockerfile.prod
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - curriculum-mapping-tool

    php:
        container_name: php
        build:
            context: .
            target: php
            dockerfile: Dockerfile.prod
        volumes:
            - .:/var/www/html
        networks:
            - curriculum-mapping-tool

    mysql:
        container_name: mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - curriculum-mapping-tool-mysql:/var/lib/mysql
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        networks:
            - curriculum-mapping-tool

    composer:
        image: composer:latest
        container_name: composer
        volumes:
          - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
          - php
        networks:
          - curriculum-mapping-tool

    npm:
        container_name: npm
        image: node:20.15
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

networks:
    curriculum-mapping-tool:
        driver: bridge

volumes:
    curriculum-mapping-tool-mysql:
        driver: local
