# remember to "Register New File Type Association" in PhpStorm or your IDE to get syntax highlighting and other file helpers

FROM nginx:stable AS nginx

COPY nginx.prod.default.conf /etc/nginx/conf.d/default.conf


FROM php:8.2-fpm AS php

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions pdo pdo_mysql intl zip pcntl
