services:
    php:
        image: serversideup/php:8.2-fpm-nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/html
            - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - curriculum-mapping-tool-mysql:/var/lib/mysql
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    curriculum-mapping-tool:
        driver: bridge

volumes:
    curriculum-mapping-tool-mysql:
        driver: local
